version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: cyberdas/yamdb_final:latest
    restart: always
    volumes:
      - static_volume:/code/static
    depends_on:
      - db 
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/code/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
